"""Export the star schema as Parquet for Databricks (offline stub).

Writes each warehouse table to a Parquet file plus a Databricks SQL script
that registers them as external/managed Delta-style tables. Parquet writing
requires ``pyarrow``; if it is absent we fall back to CSV so the stub never
hard-fails. No Databricks connection is ever attempted.
"""
from __future__ import annotations

from pathlib import Path

from ..schema.star import StarSchema


def _has_pyarrow() -> bool:
    try:
        import pyarrow  # noqa: F401

        return True
    except Exception:
        return False


def export_databricks_parquet(star: StarSchema, out_dir: Path) -> Path:
    """Write Parquet (or CSV fallback) files plus a Databricks SQL loader."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    use_parquet = _has_pyarrow()
    ext = "parquet" if use_parquet else "csv"

    for name, df in star.tables().items():
        target = out_dir / f"{name}.{ext}"
        if use_parquet:
            df.to_parquet(target, index=False)
        else:
            df.to_csv(target, index=False)

    script = out_dir / "databricks_load.sql"
    lines = [
        "-- Auto-generated by pipeforge (offline stub). No connection required.",
        f"-- Files written as .{ext}. Upload to a Volume/DBFS path, then:",
        "",
    ]
    for name in star.tables():
        lines.append(
            f"CREATE OR REPLACE TABLE pipeforge.{name} AS "
            f"SELECT * FROM read_files('/Volumes/pipeforge/{name}.{ext}');"
        )
    script.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_dir
