"""Generate Snowflake DDL for the star schema (offline stub).

This produces a ``.sql`` file with ``CREATE TABLE`` statements and matching
``COPY INTO`` templates. It does NOT connect to Snowflake and needs no
credentials -- it just maps pandas dtypes to Snowflake types so you have a
ready-to-run script if you later choose to load the data.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from ..schema.star import StarSchema

_TYPE_MAP = {
    "int64": "NUMBER(38,0)",
    "Int64": "NUMBER(38,0)",
    "float64": "FLOAT",
    "bool": "BOOLEAN",
    "datetime64[ns]": "TIMESTAMP_NTZ",
    "object": "VARCHAR",
    "string": "VARCHAR",
}


def _sf_type(dtype: str) -> str:
    return _TYPE_MAP.get(dtype, "VARCHAR")


def _ddl_for(name: str, df: pd.DataFrame) -> str:
    cols = ",\n".join(
        f"    {col} {_sf_type(str(dtype))}" for col, dtype in df.dtypes.items()
    )
    return (
        f"CREATE OR REPLACE TABLE {name} (\n{cols}\n);\n"
        f"-- Load with your own stage:\n"
        f"-- COPY INTO {name} FROM @my_stage/{name}.parquet "
        f"FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;\n"
    )


def export_snowflake_ddl(star: StarSchema, out_dir: Path) -> Path:
    """Write a Snowflake DDL script for all warehouse tables."""
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "snowflake_schema.sql"

    parts = [
        "-- Auto-generated by pipeforge (offline stub). No connection required.",
        "-- CREATE WAREHOUSE / DATABASE / SCHEMA as needed before running.",
        "",
    ]
    for name, df in star.tables().items():
        parts.append(_ddl_for(name, df))
    target.write_text("\n".join(parts), encoding="utf-8")
    return target
