"""Generate Snowflake DDL for the star schema from the declared schema.

The DDL is derived from the single source of truth in
:mod:`pipeforge.schema.warehouse` (the same typed SQLAlchemy tables the load
stage creates), *not* from pandas-inferred dtypes. That means the exported
Snowflake schema can never silently drift from the live SQLite/Postgres
warehouse -- a dedicated data-contract test asserts they agree.

It produces a ``.sql`` file with ``CREATE OR REPLACE TABLE`` statements
(including primary keys, and foreign keys fact -> dimensions) plus matching
``COPY INTO`` templates. It never connects to Snowflake and needs no
credentials.
"""
from __future__ import annotations

from pathlib import Path

from sqlalchemy import (
    Boolean,
    Date,
    Float,
    Integer,
    Numeric,
    String,
    Table,
)

from ..schema import warehouse as wh
from ..schema.star import StarSchema


def _sf_type(column) -> str:
    """Map a declared SQLAlchemy column type to a Snowflake type."""
    t = column.type
    if isinstance(t, Integer):
        return "NUMBER(38,0)"
    # Float is a subclass of Numeric in SQLAlchemy, so test it first.
    if isinstance(t, Float):
        return "FLOAT"
    if isinstance(t, Numeric):
        precision = getattr(t, "precision", None) or 18
        scale = getattr(t, "scale", None) or 2
        return f"NUMBER({precision},{scale})"
    if isinstance(t, Boolean):
        return "BOOLEAN"
    if isinstance(t, Date):
        return "DATE"
    if isinstance(t, String):
        length = getattr(t, "length", None)
        return f"VARCHAR({length})" if length else "VARCHAR"
    return "VARCHAR"


def snowflake_column_type(column) -> str:
    """Public helper used by the data-contract test."""
    return _sf_type(column)


def _ddl_for(table: Table) -> str:
    lines: list[str] = []
    for col in table.columns:
        nullable = "" if col.nullable else " NOT NULL"
        lines.append(f"    {col.name} {_sf_type(col)}{nullable}")

    pk = [c.name for c in table.primary_key.columns]
    if pk:
        lines.append(f"    PRIMARY KEY ({', '.join(pk)})")

    for fk in table.foreign_keys:
        lines.append(
            f"    FOREIGN KEY ({fk.parent.name}) "
            f"REFERENCES {fk.column.table.name} ({fk.column.name})"
        )

    body = ",\n".join(lines)
    return (
        f"CREATE OR REPLACE TABLE {table.name} (\n{body}\n);\n"
        f"-- Load with your own stage:\n"
        f"-- COPY INTO {table.name} FROM @my_stage/{table.name}.parquet "
        f"FILE_FORMAT = (TYPE = PARQUET) MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;\n"
    )


def export_snowflake_ddl(star: StarSchema, out_dir: Path) -> Path:
    """Write a Snowflake DDL script for all warehouse tables.

    ``star`` is accepted for API compatibility, but the DDL is generated from
    the declared schema so it reflects the real column types/constraints.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "snowflake_schema.sql"

    parts = [
        "-- Auto-generated by pipeforge from the declared warehouse schema.",
        "-- (offline stub -- no connection required).",
        "-- CREATE WAREHOUSE / DATABASE / SCHEMA as needed before running.",
        "",
    ]
    # FK-safe order: dimensions before the fact.
    for table in wh.STAR_TABLES:
        parts.append(_ddl_for(table))
    target.write_text("\n".join(parts), encoding="utf-8")
    return target
